---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: postgres-operator
spec:
  interval: 5m
  chart:
    spec:
      version: "5.3.x"
      chart: ./helm/install
      sourceRef:
        kind: GitRepository
        name: postgres-operator
        namespace: flux-system
      interval: 60m
  releaseName: postgres-operator
  targetNamespace: postgres-operator
  install:
    createNamespace: true
  values:
    debug: false
    resources:
      controller:
        requests:
          cpu: 10m
          memory: 128Mi
        limits:
          cpu: 50m
          memory: 512Mi
      upgrade:
        requests:
          cpu: 10m
          memory: 128Mi
        limits:
          cpu: 50m
          memory: 512Mi