---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:
    type: local
    purpose: chess-db
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /run/desktop/mnt/host/c/k8s/db
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-backup
  labels:
    type: local
    purpose: chess-backup
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /run/desktop/mnt/host/c/k8s/backup
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: backend-db
  namespace: chess-with-actors
spec:
  postgresVersion: 15
  instances:
  - name: backend-db
    replicas: 1
    dataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      selector:
        matchExpressions:
        - key: purpose
          operator: In
          values:
          - chess-db
      resources:
        requests:
          storage: 1Gi
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        cpu: 50m
        memory: 512Mi
  
  backups:
    pgbackrest:
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - ReadWriteOnce
            selector:
              matchExpressions:
              - key: purpose
                operator: In
                values:
                - chess-backup
            resources:
              requests:
                storage: 1Gi