apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: chess-with-actors
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chess-backend
  template:
    metadata:
      labels:
        app: chess-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: chess-cluster
      containers:
        - name: backend
          image: aaronjamesford/chess-backend:main-40 # {"$imagepolicy": "flux-system:chess-backend"}
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
            requests:
              memory: "200Mi"
              cpu: "200m"
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet:
              path: "/metrics"
              port: 80
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/metrics"
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: ProtoActor__AdvertisedHost
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
