apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: '20.6.x'
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: default
      interval: 6h
  values:
    ports:
      pg:
        port: 85432
        expose: true
        exposedPort: 5432
        protocol: TCP