---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: chess-api
  namespace: flux-system
spec:
  image: aaronjamesford/chess-api
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: chess-api
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: chess-api
  filterTags:
    pattern: '^main-(?P<build>\d*)'
    extract: '$build'
  policy:
    numerical:
      order: asc