---
apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rabbit-operator
  namespace: flux-system
spec:
  targetNamespace: rabbitmq-system
  interval: 10m0s
  path: ./config/installation
  prune: true
  sourceRef:
    kind: GitRepository
    name: rabbit-operator